---
name: CI tests

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build dev image
      run: docker compose -f dockerfiles/docker-compose-ci.yaml build
    - name: Run tests in docker-image
      run: docker compose -f dockerfiles/docker-compose-ci.yaml run microcosm-web-python-test pytest core/tests/tests.py
