---
name: CI tests

env:
  DJANGO_SETTINGS_MODULE: microweb.settings

on:
  push:

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '2.7'
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest core/tests/tests.py
